import pygame
import sys
pygame.init()

white=(255,255,255)
black=(0,0,0)
red=(255,0,0)
yellow=(255,255,0)

w = 480
h = 640 

pad=pygame.display.set_mode((w,h))
pygame.display.set_caption("sdsdad")
#---------------------------------------이미지 로드 함수 ----------------------------------------#

def img_load(obj):
    img = pygame.image.load('images/'+str(obj)+'.png')
    img_size = img.get_rect().size
    return img, img_size[0], img_size[1]
#------------------------------------------------------------------------------------------------#



bg = img_load('bgs')[0]
pad.blit(bg,(0,0))




p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.84,h*0.1))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.84,h*0.2))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.84,h*0.3))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.84,h*0.4))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.84,h*0.5))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.84,h*0.6))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.84,h*0.7))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.84,h*0.8))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.84,h*0.9))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.84,h*0.10))

p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.74,h*0.1))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.74,h*0.2))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.74,h*0.3))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.74,h*0.4))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.74,h*0.5))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.74,h*0.6))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.74,h*0.7))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.74,h*0.8))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.74,h*0.9))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.74,h*0.10))

p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.64,h*0.1))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.64,h*0.2))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.64,h*0.3))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.64,h*0.4))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.64,h*0.5))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.64,h*0.6))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.64,h*0.7))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.64,h*0.8))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.64,h*0.9))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.64,h*0.10))

p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.54,h*0.1))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.54,h*0.2))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.54,h*0.3))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.54,h*0.4))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.54,h*0.5))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.54,h*0.6))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.54,h*0.7))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.54,h*0.8))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.54,h*0.9))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.54,h*0.10))

p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.44,h*0.1))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.44,h*0.2))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.44,h*0.3))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.44,h*0.4))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.44,h*0.5))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.44,h*0.6))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.44,h*0.7))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.44,h*0.8))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.44,h*0.9))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.44,h*0.10))

p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.34,h*0.1))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.34,h*0.2))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.34,h*0.3))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.34,h*0.4))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.34,h*0.5))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.34,h*0.6))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.34,h*0.7))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.34,h*0.8))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.34,h*0.9))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.34,h*0.10))

p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.24,h*0.1))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.24,h*0.2))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.24,h*0.3))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.24,h*0.4))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.24,h*0.5))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.24,h*0.6))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.24,h*0.7))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.24,h*0.8))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.24,h*0.9))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.24,h*0.10))

p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.14,h*0.1))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.14,h*0.2))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.14,h*0.3))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.14,h*0.4))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.14,h*0.5))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.14,h*0.6))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.14,h*0.7))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.14,h*0.8))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.14,h*0.9))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.14,h*0.10))

p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.04,h*0.1))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.04,h*0.2))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.04,h*0.3))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.04,h*0.4))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.04,h*0.5))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.04,h*0.6))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.04,h*0.7))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.04,h*0.8))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.04,h*0.9))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.04,h*0.10))

p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.04,h*0.1))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.04,h*0.2))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.04,h*0.3))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.04,h*0.4))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.04,h*0.5))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.04,h*0.6))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.04,h*0.7))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.04,h*0.8))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.04,h*0.9))
p, pw, ph =  img_load('faker')
pad.blit(p,(w*0.04,h*0.10))



r, rw, rh =  img_load('rock01')
pad.blit(r,(w*0.42,h*0.1))

pygame.display.update()

while True:
    for event in pygame.event.get():
        if event.type==pygame.QUIT:
            pygame.quit()
            sys.exit()
